### PR TITLE
Adding boiler plate; placing branch into GitHub repo

### PR DESCRIPTION
**Pull request by CalebRose**
Okay team let's approve this pretty pls with sugar on top

### CODE REVIEW

**Comment by EmmanuelZapata** [comment]
Looks good to me!

**Review by EmmanuelZapata — APPROVED** [review]

**Review by toobaditstaken — APPROVED** [review]
looks good

**Comment by humanhitmarker** [comment]
good to go

**Comment by CalebRose** [comment]
I think you accidentally closed it

**Comment by humanhitmarker** [comment]
MY BAD

**Review by humanhitmarker — APPROVED** [review]

**Comment by CalebRose** [comment]
We good, no worries

**Pull request closed without merging**
